## Matrices con Numpy ##

NumPy significa Numeric Python, este es un paquete para cómputo cientifico. Y sirve para:
- Utilizar vectores y matrices (*ndarray*)
- Cálculos estadísticos y matemáticos

Numpy array es un objeto de **matriz n-dimensional**. Tiene forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones. Se admite el mismo tipo de datos en un Array, por ejemplo, solo números o solo texto.

**Propiedades:**

-**Dimensión:** Nivel de profundidad.

-**Shape:** Número de elementos de cada dimensión. "Forma" (filas,columnas)

Creamos estas matrices y vectores mediante el comando *np.array*.

In [6]:
import numpy as np

Podemos crear ndarray con listas o tuplas, la diferencia está en que una se podrá modificar y la otra no.

In [3]:
# Crear ndarray con lista

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
#Este sería un array unidimensional
a.ndim

1

In [8]:
#Crear ndarray con tupla
b = np.array((1,2,3,4))
b


array([1, 2, 3, 4])

Podemos crear un array de 0 dimensiones.

In [11]:
# array de 0 dimensiones (punto)

a0 = np.array(16)

a0

array(16)

In [10]:
a0.ndim

0

Para crear un array de dos dimensiones hay que poner por cada fila una lista.


In [12]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2.ndim

2

In [17]:
a2.shape # Dos filas y tres columnas

(2, 3)

In [20]:
a3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a3  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

No confundir, la matriz anterior continua siendo de dos dimensiones, solo que ahora tiene más filas.

In [21]:
a3.ndim

2

Para realizar una matriz de 3 dimensiones debemos crear los "pisos" de esta matriz, y esto se realiza poniendo las filas de este piso en otra lista.

In [23]:
a3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
a3d.ndim

3

In [26]:
# El primer 2 se refiere a los #pisos, el segundo a la cantida de filas, y el tercero las columnas
a3d.shape

(2, 2, 3)

Para seleccionar elementos de este array debería ir eligiendo por partes, primero el "piso", luego la fila y por último la columna.

In [27]:
a3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3d[0][1]

array([4, 5, 6])

In [29]:
a3d[0][1][0]

4

Podemos realizar operaciones con arrays, como multiplicaciones por escalares, o entre arrays, pero estos últimos deben tener la misma cantidad de filas y columnas.

In [30]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a4 = a3*2
a4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# Si multiplico a3 y a2 me da un error debido a que no tienen las mismas cantidad de filas y columnas
a3*a2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

También se puede realizar un promedio con todos los valores de una matriz.

In [38]:
a4.mean()

10.0

## Comparación NumPy contra las listas propias de Python ##

La diferencia está en que NumPy ocupa menos espacio de memoria que las listas de Python para realizar la misma operación. Y por otro lado es más rápido.

En el ejemplo siguiente creamos una lista de 1000 elementos y calculamos la memoria asignada a esta lista con respecto a estas dos metodologías.

In [40]:
import sys
S = range(1000)
print("Resultado lista de Python: ")
print(sys.getsizeof(5)*len(S))
print()

Resultado lista de Python: 
28000



In [41]:
D = np.arange(1000)
print("Resultado NumPy array: ")
print(D.size*D.itemsize)

Resultado NumPy array: 
4000


Ahora analizaremos la rapidez, crearemos dos listas con un millón de datos cada una y crearemos en base a ellas dos array. Con esto calcularemos la rapidez en crear estos array con ambas metodologías.

In [61]:
import time
SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)] # re complicado nae
print("Resultado lista de Python:")
print((time.time()-start)*1000)
print()
start = time.time()
result = A1+A2
print("Resultado NumPy array: ")
print((time.time()-start)*1000)

Resultado lista de Python:
201.01666450500488

Resultado NumPy array: 
73.00758361816406


## Comandos NumPy ##

Podemos definir el tipo de variable que vamos a utilizar (int, float, string, etc).

In [62]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


En ocaciones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se pueden inicializar matrices con unos o ceros, pero también se pueden hacer matrices que se llenen con valores espaciados uniformemente, valores constantes o aleatorios.

Alguna de las instrucciones para crear este tipo de matrices son las siguientes:

In [64]:
#Matriz donde todos los valores son 1
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
#Matriz donde todos los valores sean ceros
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [66]:
#Matriz con valores aleatorios
aleatorios = np.random.random((3,4))
print(aleatorios)

[[0.53554846 0.39147309 0.38775994 0.71342713]
 [0.44558716 0.78267961 0.02974783 0.51914364]
 [0.40230246 0.71864516 0.34882256 0.00950856]]


In [72]:
#Matriz vacía
vacia = np.empty((3,2))
print(vacia)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]
 [2.12199579e-313 2.54639495e-313]]


In [74]:
#Matriz con el mismo valor en todas las posiciones
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [76]:
#Matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)

espacio2 = np.linspace(0,2,5)
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


In [77]:
#Matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Para inspeccionar matrices tenemos los siguientes códigos:

In [78]:
#Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
a.ndim

2

In [85]:
#Tipo de datos de una matriz
a = np.array([1.2,2.0,3.55], dtype=np.float64)
a.dtype

dtype('float64')

In [87]:
#Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [89]:
#Transpuesta de una matriz
a = np.array([(1,2,3),(4,5,6)])
print("Matriz original")
print(a)
a=a.reshape(3,2)
print("Matriz Transpuesta")
print(a)

Matriz original
[[1 2 3]
 [4 5 6]]
Matriz Transpuesta
[[1 2]
 [3 4]
 [5 6]]


In [92]:
#Obtener todos los datos de una columna
a[0:,1]

array([2, 4, 6])

In [93]:
#Encontrar el mínimo, máximo y la suma 
a = np.array([2,4,8])
print(a.min())
print(a.max())
print(a.sum())

2
8
14


In [95]:
#Raiz cuadrada y desviación estandar
a = np.array([(1,2,3),(3,4,5)])
print("Raiz cuadrada")
print(np.sqrt(a))
print("Desviación estandar")
print(np.std(a))

Raiz cuadrada
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
Desviación estandar
1.2909944487358056
